services:
  - type: web
    name: aadhaar-telegram-bot
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python ad.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8777443945:AAGM_f-WtydhbzRDZ1bgMt1X6ATu_oushHs"
      - key: ANTI_CAPTCHA_KEY
        value: "b05b20aabb26049c7c730cdbdd682153"
      - key: PORT
        value: "10000"
